### ISSUE TITLE
how to select root path?

### ISSUE THREAD

**Issue by qianmoQ** [inspirsea/personal#1]

**Comment by inspirsea** [comment]
Im sorry, but could you be a bit clearer i dont know what you are asking?

**Comment by qianmoQ** [comment]
![image](https://user-images.githubusercontent.com/20521442/58685562-bffba900-83ae-11e9-9054-f914d9c38cd3.png)
how to get **Neutural** value?

**Comment by inspirsea** [comment]
The parents dosent have selectable values, as the are meant to label the hierarchy. You can use MultiSelect to get all values beneath it. Feel free to open a feature request.

**Comment by qianmoQ** [comment]
I use it in the article list, but I can't choose the parent level, I may not try it out, thanks
